COPY:	START	1000						
FIRST:	STL		RETADR					
CLOOP:	
		JSUB	RDREC		
		+LDA		LENGTH
		RESB	100
		COMP	ZERO
		JEQ		ENDFIL
		LDB	#CLOOP
		BASE	CLOOP	
		JSUB	WRREC
		RESW	1		
		J		CLOOP	
ENDFIL:	LDA		EOF		
		STA		BUFFER
		LDA		THREE
		STA		LENGTH
		RESB	190
		JSUB	WRREC
		NOBASE					
		LDL		RETADR	
		RESW	20			
		RSUB						
EOF:	BYTE	C'EOF'
THREE:	WORD	3
ZERO:	WORD	0
		HIO
		TIXR	A
RETADR:	RESW	1
		RSUB
LENGTH:	RESW	1
		ADD	@EOF						
BUFFER:	RESB	4096						
.
.		SUBROUTINE TO READ RECORD INTO BUFFER
.
RDREC:	LDX		ZERO					
		LDA		ZERO				
RLOOP:	TD		INPUT					
		JEQ		RLOOP				
		RD		INPUT
		COMPR	PC  ,  SW
EXIT:	STX		LENGTH
INPUT:	BYTE	X'F1'
MAXLEN:	WORD	4096
.
.		SUBROUTINE TO WRITE RECORD FROM BUFFER
.
WRREC:	LDX		ZERO
WLOOP:	TD		OUTPUT
		JLT		WLOOP
HEY:		RSUB
THERE:		TIXR		A
OUTPUT:	BYTE	X'05'		
		END


